import type { InferGetServerSidePropsType, GetServerSideProps } from "next";
import Head from "next/head";

type Entry = {
  who_region: string;
  week_of_collection: string;
  lineage: string;
  lineage_proportion_per_week: number;
};

type Week = {
  date: string | null;
  variants: Variant[] | [];
};

type Variant = {
  name: string;
  percentage: number;
};

const sortData = (data: Entry[]) => {
  let sorted: Week[] = [];

  let currentWeek: Week = {
    date: null,
    variants: [],
  };

  data.forEach((item) => {
    if (currentWeek.date === null) currentWeek.date = item.week_of_collection;

    if (currentWeek.date !== item.week_of_collection) {
      sorted = [...sorted, currentWeek];
      currentWeek = {
        date: item.week_of_collection,
        variants: [],
      };
    }

    const variant: Variant = {
      name: item.lineage,
      percentage: item.lineage_proportion_per_week,
    };

    currentWeek.variants = [...currentWeek.variants, variant];
  });

  return sorted;
};

export default function Home({
  data,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        {data.map((item, i) => (
          <div key={i}>
            <h1 className="text-3xl font-bold">{item.date}</h1>
            <p>
              {item.variants.map((variant, ii) => (
                <p key={ii}>
                  {variant.name}, {variant.percentage}
                </p>
              ))}
            </p>
          </div>
        ))}
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps<{
  data: Week[];
}> = async () => {
  const res = await fetch(
    "https://covid.cdc.gov/covid-data-tracker/COVIDData/getAjaxData?id=TGS_pool_variant_proportions_data"
  );

  // eslint-disable-next-line
  const {
    TGS_pool_variant_proportions_data,
  }: { TGS_pool_variant_proportions_data: Entry[] } = await res.json();

  const sortedData = sortData(TGS_pool_variant_proportions_data);

  return {
    props: {
      data: sortedData,
    },
  };
};
